version = 0.1
[default.deploy.parameters]
stack_name = "Rutastic"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d9t24k9eyhtf"
s3_prefix = "Rutastic"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
role_arn = "arn:aws:iam::260124700194:role/LabRole"
parameter_overrides = "DBDevEndpointSourceCIDR=\"81.43.214.123/32\" LambdaExecutionRoleArn=\"arn:aws:iam::260124700194:role/LabRole\" RutasticAPIProductionStageName=\"prod\" GitHubPersonalAccessToken=\"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\""
image_repositories = []
confirm_changeset = true
