POST https://{{apiEndpoint}}/{{apiStage}}/usuarios
Content-Type: application/json

{
  "username": "testuser-pablogpz"
}

###

POST https://{{apiEndpoint}}/{{apiStage}}/usuarios
Content-Type: application/json

{
  "username": "really-long-username-that-wont-fit"
}

###
